### ISSUE TITLE
Add easy way to ignore specific exceptions.

### ISSUE THREAD

**Issue by kokanin** [SkyLined/BugId#20]
- easy way to ignore/pass certain / custom exceptions
- easy way of ignoring cpu usage bugs (my fuzzer is shitty :D)

**Comment by SkyLined** [comment]
Thanks for the feedback. In the future, please open a separate bug for each feature request, as this makes it easier to track progress for each individual request.

Re: easy way of ignoring cpu usage bugs

You can do this by adding `--nExcessiveCPUUsageCheckInitialTimeout=null`, or modifying the value in `dxConfig.py`. If you do, BugId will not check for CPU excessive usage at all. You can also consider defining what you consider excessive using `nExcessiveCPUUsageCheckInterval` and `nExcessiveCPUUsagePercent` in `dxBugIdConfig.py` in cBugId. Higher values mean less chance of false positives.

**Comment by SkyLined** [comment]
Re: easy way to ignore/pass certain / custom exceptions

This is not yet supported. You may want to look at `cBugId\cCdbWrapper_fCdbStdInOutThread.py`, line 281. There is a "break" there that stops BugId from running the application in the debugger and has it report a bug (`oCdbWrapper.oBugReport`). You may want to add some code there to check if the oBugReport is for an exception you want to ignore. If it is, simply set `oCdbWrapper.oBugReport = None;` and don't "break" out of the loop: debugging will continue (if possible - if the exception is fatal, the application will terminate).

**Comment by SkyLined** [comment]
I'll use this bug to track this issue. This is not a priority for me at the moment, as I do not need it myself.

Please feel free to submit a patch that implements this, or suggest a design.

If you really need this feature, but are unable to create it yourself, please describe the exceptions you need to filter, and how I might separate them for other exceptions that should still be considered bugs. This should help me come up with a design that makes this easy to implement and use.

**Comment by SkyLined** [comment]
Current status:
* How various exceptions are handled is defined in `fsExceptionHandlingCdbCommands.py`. If you need to make changes, you should probably edit that file.
* Handling of C++ and WinRT (Originate/Transform) exceptions can be disabled through `dxConfig` by setting `bIgnoreCPPExceptions` and/or `bIgnoreWinRTExceptions` to True respectively. These two were added because they have never indicated an actual bug in my experience and Microsoft Internet Explorer and Edge throw these very frequently, which slows down BugId and can bloat the HTML Bug Report.

Again, if you have specific exceptions that you would like to be able to easily disable (i.e. through `dxConfig`), let me know and I will see about adding code to cBugId to do that.

**Comment by SkyLined** [comment]
This should be possible using "Bug Translations" (https://github.com/SkyLined/cBugId/tree/master/BugTranslations): if you translate a bug id to `None`, it won't be reported and BugId will try to continue to run the application. A good example of this can be found here:
https://github.com/SkyLined/cBugId/blob/master/BugTranslations/corpol_dll.py
