### ISSUE TITLE
TypeError("unsupported operand type(s) for +: 'NoneType' and 'NoneType'",

### ISSUE THREAD

**Issue by dmitrikaslov** [SkyLined/BugId#22]
Good day,

I was using BugID and came across an internal TypeError:
```
* T+49.6 The application was resumed successfully and is running...
ception in thread Thread-1:
aceback (most recent call last):
File "C:\Python27\lib\threading.py", line 810, in __bootstrap_inner
  self.run()
File "C:\Python27\lib\threading.py", line 763, in run
  self.__target(*self.__args, **self.__kwargs)
File "C:\Users\s\Desktop\BugID\modules\cBugId\cCdbWrapper.py", line 2
 in _fThreadWrapper
  oCdbWrapper.fInternalExceptionCallback(oException);
File "C:\Users\s\Desktop\BugID\modules\cBugId\cCdbWrapper.py", line 2
 in _fThreadWrapper
  fActivity(oCdbWrapper);
File "C:\Users\s\Desktop\BugID\modules\cBugId\cCdbWrapper_fCdbStdInOu
read.py", line 256, in cCdbWrapper_fCdbStdInOutThread
  cCdbWrapper_fbDetectAndReportVerifierErrors(oCdbWrapper, asCdbOutput):
File "C:\Users\s\Desktop\BugID\modules\cBugId\cCdbWrapper_fbDetectAnd
ortVerifierErrors.py", line 49, in cCdbWrapper_fbDetectAndReportVerifierError

  uHeapBlockEndAddress = uHeapBlockAddress + uHeapBlockSize;
peError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'

BugId run into an internal error:
TypeError("unsupported operand type(s) for +: 'NoneType' and 'NoneType'",)

Please report this issue at the below web-page so it can be addressed:
https://github.com/SkyLined/BugId/issues/new
```

**Comment by SkyLined** [comment]
Thanks for the report! I'll have a look to see what could be the problem asap.

**Comment by SkyLined** [comment]
The problem is due to Application Verifier reporting an error in a format I do not yet recognize.

In order to address this, I need to know what the Application Verifier error report looks like. If you can reproduce this issue, it would really help me if could run BugId with the command line argument `--BugId.bOutputStdOut=true`; as in `BugId.py --BugId.bOutputStdOut=true @application`, or `BugId.py --BugId.bOutputStdOut=true path\to\application`. You will see all the cdb.exe output that BugId parses, which should include a message near the end that looks somewhat similar to this:

```
===========================================================
VERIFIER STOP 0000000000000010: pid 0xBC8: corrupted start stamp 

    00000296918C1000 : Heap handle
    0000029691A65FF0 : Heap block
    000000000000000C : Block size
    00000000ABCDBBBB : Corrupted stamp
===========================================================
This verifier stop is not continuable. Process will be terminated 
when you use the `go' debugger command.
===========================================================
```

Obviously it will not look exactly the same, as BugId can't parse it: the problem you discovered is that a VERIFIER STOP is reported but there is no `Heap block` or `Block size` information in the message, hence they are both None instead of a number and the code subsequently tries to add None + None.

If you can copy+paste that message here, I should be able to improve the code so it can parse it and analyze the issue. Assuming the message is similar to the above, it should not contain any useful information about the specific bug you found (like the one above), but please check to make sure you sensor anything sensitive that might disclose your 0day.

I will also modify the code to add sanity checks and report the entire message if it cannot be parsed: that should make it easier to fix similar issues in the future.

**Comment by dmitrikaslov** [comment]
Hi

Ran it in windbg and here is the AV report error:

=======================================
VERIFIER STOP 0000000000000303: pid 0xB2C: NULL handle passed as parameter. A valid handle must be used. 

	0000000000000000 : Not used.
	0000000000000000 : Not used.
	0000000000000000 : Not used.
	0000000000000000 : Not used.


`=======================================`
This verifier stop is continuable.
After debugging it use `go' to continue.

=======================================

(b2c.ed8): Break instruction exception - code 80000003 (first chance)
verifier!VerifierStopMessageEx+0x6f0:
00007ffa`aac0b370 cc              int     3``

Is that helpful?

**Comment by SkyLined** [comment]
That's exactly what I needed! I should have a patch ready later today.

Could it be that you are running with the `FLG_ENABLE_HANDLE_EXCEPTIONS` (0x40000000) flag enabled in application verifier? That would cause Application Verifier to show these messages. AFAICT these checks and the resulting messages are not really interesting, so you may want to disable them altogether to speed things up.

**Comment by SkyLined** [comment]
Sorry for the delay, I was working on some mayor changes and needed to finish those before I could resolve this issue. Please check if the most recent version is still affected by this and reopen if so.

Thanks again for reporting this issue and helping me improve BugId!
