### ISSUE TITLE
AssertionError('sBugDescription should have been set',)

### ISSUE THREAD

**Issue by sizzop** [SkyLined/BugId#30]
I get an AssertionError when pageheap is enabled for the application I am testing. When I disable pageheap the bug is reported as a Breakpoint DoS. If I run the application manually under cdb with pageheap enabled I see that the input is causing a double free.

I'm attaching console output as a text file for more details so that it doesn't get markdown mangled.
[bugid-details.txt](https://github.com/SkyLined/BugId/files/736263/bugid-details.txt)

**Comment by SkyLined** [comment]
Thank you very much for the report!

Turns out I was not handling double-frees at all in BugId. I had already added a test for double free, but not enabled it, so I never found out that I wasn't actually detecting them.

This should be fixed in https://github.com/SkyLined/cBugId/commit/afc7b611135bf8bd2a9a6fcb65c65ad21a139535

**Comment by SkyLined** [comment]
(Obviously I improved the security impact description in a later commit).
