### ISSUE TITLE
Exception 'cErrorReport_foSpecialErrorReport_STATUS_STACK_OVERFLOW'

### ISSUE THREAD

**Issue by symeonp** [SkyLined/BugId#5]
Hi!

Here is my output from Win7 x32 when playing with a toy program:

```python
C:\class\cdf>python C:\BugId\BugId.py C:\class\cdf\cdf_reader.exe C:\crashes\cdf_reader_241406974\crash1.cdf
* The debugger is starting the application...
  Command line: C:\class\cdf\cdf_reader.exe C:\crashes\cdf_reader_241406974\crash1.cdf
* New process 1616.
* The application was started successfully and is running...
* Exception code 0xC0000005 (Access violation) was detected and is being analyzed...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\BugId\cCdbWrapper.py", line 92, in _fThreadWrapper
    fActivity(oCdbWrapper);
  File "C:\BugId\cCdbWrapper_fCdbDebuggerThread.py", line 153, in cCdbWrapper_fCdbDebuggerThread
    oCdbWrapper.oErrorReport = cErrorReport.foCreate(oCdbWrapper, uExceptionCode, sExceptionDescription);
  File "C:\BugId\cErrorReport.py", line 95, in foCreate
    oErrorReport = foSpecialErrorReport(oErrorReport, oCdbWrapper);
  File "C:\BugId\cErrorReport_foSpecialErrorReport_STATUS_ACCESS_VIOLATION.py", line 204, in cErrorReport_foSpecialErrorReport_STATUS_ACCESS_VIOLATION
    return cErrorReport_foSpecialErrorReport_STATUS_STACK_OVERFLOW(oErrorReport, oCdbWrapper);
NameError: global name 'cErrorReport_foSpecialErrorReport_STATUS_STACK_OVERFLOW' is not defined
```

Some info: It turns out that indeed this is a stack overflow (my stack is completely smashed) and I managed to reproduce this issue on Windows XP as well.

If you need more info on how to reproduce it, please let me know.
Thanks for sharing this project, it works really great with identifying the rest of my bugs.

Cheers.

**Comment by SkyLined** [comment]
Thanks for the report. I'm glad to hear it's working for most of the bugs
you're working with. I'm on holiday at the moment, so it'll be next week
before I have time to look at this issue. Sorry for the delay.

In the mean time, you may want to try putting this line at the top of the
file cErrorReport_foSpecialErrorReport_STATUS_ACCESS_VIOLATION.py:

from cErrorReport_foSpecialErrorReport_STATUS_STACK_OVERFLOW import
cErrorReport_foSpecialErrorReport_STATUS_STACK_OVERFLOW;

From a quick glance at the error, I believe that may fix your issue - good
luck!

**Comment by symeonp** [comment]
Wow that's awesome, it worked like a charm :)

```python
Error report:     EB18 StackExhaustion cdf_reader.exe!MSVCR90.dll!memcpy.html (25340 bytes)
```

Enjoy your holidays, and feel free to close the issue if you want!

**Comment by bnagy** [comment]
I just noticed this issue - just my 0.02, but a stack smash should be either an AV or Stack Buffer Overflow (eg stack cookie check fail), not Stack Exhaustion. Something seems up, here...

**Comment by SkyLined** [comment]
Please note that STATUS_STACK_OVERFLOW indicates stack exhaustion, not a stack-based buffer overrun. Unfortunately, the terminology is confusing and I attempt to use the terms "stack exhaustion" and "stack-base buffer overrun", rather than "stack overrun" and "buffer overrun".

The code attempts to detect an access violation that is triggered by stack exhaustion and not immediately reported as such. I fail to remember when I first encountered this, so I cannot give an example. But I can give a description of the situation in which this happens:

When a thread has used up all its available stack space, it can still decrease the stackpointer to below the address where the stack memory allocation begins. If it subsequently attempts to read/write to the stack, an access violation can happen. This is what was being detected.

I've removed the code as I'm not sure if it is working correctly - I will find out if I encounter this situation again. If anyone else encounters it, let me know. In that case I will attempt to rewrite the code in a way that uses the TEB to determine where the stack memory is located and provide a BugId along the lines of "AVX:Stack-EVEN"
