### ISSUE TITLE
Windows 10 - BugId error

### ISSUE THREAD

**Issue by richard-clifford** [SkyLined/BugId#84]
E:\Fuzzing>python BugId\BugId.py "firefox" "--sReportFolderPath=\"E:\\Fuzzing\\Report\"" --nApplicationMaxRunTime=10000 -- "file://Tests\fuzz-0.html"
┌─ An internal exception has occured 
**│TypeError("object of type 'NoneType' has no len()",)**
│
│  Stack:
│   0 splitdrive @ C:\Python27\lib\ntpath.py/115
│      > if len(p) > 1:
│   1 join @ C:\Python27\lib\ntpath.py/65
│      > result_drive, result_path = splitdrive(path)
│   2 fbCdbFound @ E:\Fuzzing\BugId\modules\cBugId\cBugId.py/66
│      > return os.path.isfile(os.path.join(dxConfig["sDebuggingToolsPath_%s" % sCdbISA], "cdb.exe"));
│   3 fMain @ BugId\BugId.py/784
│      > if not cBugId.fbCdbFound(sCdbISA):
│   4 BugId\BugId.py/977
│      > fMain(sys.argv[1:]);
└────────────────────────────────────────────────────────────────

┌─ Version information ─────────────────────────────────────────────────────────────────
│ ∙ BugId version: 2018-10-17 07:26 (in trial period).
│ ∙ mFileSystem version: 2018-08-30 20:06 (in trial period).
│ ∙ mWindowsAPI version: 2018-06-18 20:12 (in trial period).
│ ∙ cBugId version: 2018-10-17 07:18 (in trial period).
│ ∙ mProductDetails version: 2018-09-24 11:57 (in trial period).
│ ∙ oConsole version: 2018-09-24 11:58 (in trial period).
│ ∙ Windows version: Windows 10 Pro release 1803, build 17134 x64.
│ ∙ Python version: 2.7.15 x64.
└────────────────────────────────────────────────────────────────

┌─ Software license warning ────────────────────────────────────────────────────────────────
│ You have no license for mFileSystem and your trial period will expire on 2018-11-19
│ You have no license for mWindowsAPI and your trial period will expire on 2018-11-19
│ You have no license for cBugId and your trial period will expire on 2018-11-19
│ You have no license for BugId and your trial period will expire on 2018-11-19
│ You have no license for mProductDetails and your trial period will expire on 2018-11-19
│ You have no license for oConsole and your trial period will expire on 2018-11-19
└────────────────────────────────────────────────────────────────

**Comment by SkyLined** [comment]
Thanks,

The root cause is that `sDebuggingToolsPath_x64` in `dxConfig.py` is None. This means you probably do not have Debugging Tools for Windows installed. However, IIRC BugId should notice you do not have it installed and report it in a much more obvious manner. So, I'll try to figure out how this could have happened.

Could you let me know if you have Debugging Tools for Windows installed and in what folder?

**Comment by SkyLined** [comment]
Ah, I noticed the bug actually happens when the code is trying to see if you have Debugging Tools installed and crashes because you probably do not, or at least not in a path where it can find it. This bug is easy to fix, but after the fix BugId will tell you it cannot find Debugging Tools for Windows, so you will still need to install that. Or, if you installed the SDK in a non-default path, you have to change the `dxConfig.py` file to let BugId know where to find it.

**Comment by SkyLined** [comment]
I've updated the code to address this issue.
https://github.com/SkyLined/cBugId/commit/1f50df92130344c0a50d4bbd046e6685b5b1b21c
I'll integrate this fix into BugId the next time I create a release.

**Comment by richard-clifford** [comment]
Ah nice one! I thought I had them installed but I can double check. Sorry for the late reply, been hectic. I appreciate the effort and the quick fix!
