### ISSUE TITLE
Invalid Command Line

### ISSUE THREAD

**Issue by aleks-zer0** [SkyLined/BugId#85]
Python version: 2.7.15 x64
BugID Version: 2018-10-17

When fuzzing EDGE on win10 x64 version 1803(build 17134.376), sometimes this happens:
![bugid_edge_bug_sample](https://user-images.githubusercontent.com/37329884/47671650-4e594380-dbb0-11e8-8a15-b141b938e585.png)
Then it waits for user to press OK, and a few more minutes later, it restarts and start generating new .html tests. Btw, i'm using the setup described on the blog: https://bugid.skylined.nl/20181017001.html

**Comment by aleks-zer0** [comment]
Correction, the bug doesn't happen just sometimes, it happens in 8 out of 10 iterations. Something about UWP app debugging?

**Comment by aleks-zer0** [comment]
@SkyLined @j00sean

**Comment by aleks-zer0** [comment]
Thanks. So as i can see on the thread, no solution is found yet :(

**Comment by SkyLined** [comment]
Yes: the problem is in Microsoft Debugging Tools for Windows AFAICT so I cannot fix it. I also do not know what causes it, nor do I know how to work around it.

I do have plans to allow BugId to work as a JIT debugger which should make this problem non-existent. Note that this would be a mayor code rewrite which will require quite some time to implement so don't hold your breath.

You can create a wrapper for EdgeHTML and use that; this will allow you to fuzz Edge's HTML rendering and JavaScript engines without actually using Edge. That should be faster and less error prone. I have plans to create and publish such a wrapper myself for this purpose.

**Comment by j00sean** [comment]
https://github.com/j00sean/SimpleWebView

**Comment by SkyLined** [comment]
I'll leave this open even if I cannot fix it as it has not been resolved and this bug might help others work around it.

**Comment by aleks-zer0** [comment]
Just figured out that on fresh win10 x64 v1703.15063.608 this is **not an issue** and works just fine, but after updating to 1803.17134.376 it starts happening again. It seems like EDGE is the actual problem, maybe they switched it to full-UWP app or something?

**Comment by j00sean** [comment]
yeah man, this annoying issue starts with April updates as i posted on other issue. Anyone has tested on 1809? I have no received the update and it's not available yet from free vms (https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/). I read that this update was retired by MS. But it should be available now or very soon.

**Comment by SkyLined** [comment]
Work around: I confirmed the following allows you to use BugId with Edge:

1) Start Edge (either in BugId or manually)
2) Terminate browser_broker.exe once it is started.
3) Terminate Edge
4) Start Edge in BugId.

I'll see if I can add code to do this automatically.

**Comment by aleks-zer0** [comment]
Still not working for me, same message pops up. Also, immediately after killing browser_broker.exe, it spawns again :(

**Comment by SkyLined** [comment]
> EDIT2: Ok, it pops again :( i would really like to understand what is happening here and why it works in 1 out of 10 cases..

Oh, we all do.... we all do... :'(

**Comment by SkyLined** [comment]
I think this issue no longer exists, please let me know if it does.
