### ISSUE TITLE
Firefox hangs?

### ISSUE THREAD

**Issue by aleks-zer0** [SkyLined/BugId#88]
Hi again. I've been using your setup from [Fuzz in sixty seconds](https://bugid.skylined.nl/20181017001.html) tutorial for the past two months successfully on firefox. Yesterday after updating BugId to laters ver, it just hangs at "Loading test 0" tab caption and never continue loading remaining .html tests. This is console output:
![firefox_error](https://user-images.githubusercontent.com/37329884/50989138-d6dc5480-150e-11e9-848c-15f0d8b60cb4.png)
What am i doing wrong here? Did something significant got changed in the latest revision and i somehow missed it? Btw, i'm using Win 10 Pro x64 - v1803.

**Comment by SkyLined** [comment]
Hi,

That sounds like a problem with the fuzzer and not BugId but since I do not have a bug tracker for that, let's try to solve it here.

Unfortunately, that screenshot shows two lines of debug output from JavaScript running in Firefox; this does not provide me with information that might relate to your issue, so I cannot help you solve your problem with the information given.

You mentioned you updated to the latest version; what version of BugId are you using exactly? Please run `BugId.py --version` and copy+paste the output here. That would allow me to test with the same version.

If you want to make sure the problem is not in BugId you should use a [release](https://github.com/SkyLined/BugId/releases) version and not the latest main branch. I frequently commit breaking changes to the main branch (and sometimes broken code) without any explicit warning. It only makes sense to use the latest main branch directly if you are developing BugId, testing a specific bug fix or want to try a new feature that's not in release yet.

**Comment by SkyLined** [comment]
Sorry, last week was my first week working at Intel, so I haven't had time to look at this yet.

I've made some changes to BugId that are not yet in the release version, which is why you are seeing the `latest product details JSON file from repository root contains an unexpected value`-errors. That is nothing to worry about and shouldn't affect anything but the latest version check.

Once I've settled in at Intel I'll set up a clean VM and test if I can reproduce the issue. It may be another week before I find some time though.  I apologize for these delays; I try to handle issues asap.

**Comment by SkyLined** [comment]
I released a new version but did not have time to check if it fixes this issue. Please let me know if you still experience this issue with the latest version.

**Comment by aninax** [comment]
Hi, I am experiencing same issue with Firefox, and Edge with new BugID version. IE is working ok.

**Comment by SkyLined** [comment]
So I finally had some time to look at this and it turns out to be quite simple and easy to fix. The problem was in the `index.html` file that facilitates loading all the fuzzed files. It attempted to call `addEventListener` on the `window` object of an `iframe`. Some browsers treat pages loaded from different files on the local file system as being in different origins. This causes that call to throw an exception, which stopped the `index.html` file from loading the fuzzed files.

The fix was to wrap the `addEventListener` call in a `try ... catch` block to catch and ignore the exception. I have updated the blog post. The new index.html file can be downloaded [here](https://blog.skylined.nl/20181017001/index.html).

**Comment by SkyLined** [comment]
FYI This was the line that reported the underlying issue:
```
* Sub process 8464/0x2110 (firefox.exe): debug┬[JavaScript Error: "SecurityError: Permission denied to access property "addEventListener" on cross-origin object" {file: "file:///G:/Fuzzing/Tests/index.html" line: 18}]
                                              └fLoadNext@file:///G:/Fuzzing/Tests/index.html:18:9
```
